-- Generated by scripts/build-sql.mjs; do not edit this file by hand.
-- Local taxonomy + resolver SHA-256: 98f66c48f1e41f36ee4ef59b501896eb1978f244c61c479fdf31f7f8d732a390
-- Standard SQL; synthetic inputs only. One JSON lead per UDF invocation.
CREATE TEMP FUNCTION resolve_crm_lead(lead_json STRING, options_json STRING)
RETURNS STRUCT<
  source_system STRING,
  source_scope STRING,
  lead_key STRING,
  created_at STRING,
  channel STRING,
  taxonomy_version STRING,
  rule STRING,
  attribution_basis STRING,
  match_key STRING,
  confidence STRING,
  quality_status STRING,
  ad_source_system STRING,
  ad_source_scope STRING,
  ad_key STRING,
  campaign_key STRING,
  ad_match_method STRING,
  ad_scope_method STRING,
  ad_confidence STRING,
  ad_match_status STRING,
  network_id STRING,
  raw_evidence STRUCT<click_ids STRUCT<dclid STRING, gclid STRING, gbraid STRING, wbraid STRING, msclkid STRING, fbclid STRING, ttclid STRING, rdt_cid STRING, li_fat_id STRING, twclid STRING, epik STRING, sccid STRING, srsltid STRING>, current_utm STRUCT<utm_source STRING, utm_medium STRING, utm_campaign STRING, utm_content STRING, utm_term STRING>, first_touch_utm STRUCT<utm_source STRING, utm_medium STRING, utm_campaign STRING, utm_content STRING, utm_term STRING>, first_touch_click_ids STRUCT<dclid STRING, gclid STRING, gbraid STRING, wbraid STRING, msclkid STRING, fbclid STRING, ttclid STRING, rdt_cid STRING, li_fat_id STRING, twclid STRING, epik STRING, sccid STRING, srsltid STRING>, native_channel STRING>,
  is_attribution_primary BOOL,
  candidate_ads ARRAY<STRUCT<source_system STRING, source_scope STRING, ad_key STRING, campaign_key STRING>>,
  candidate_ad_keys ARRAY<STRING>,
  _selected_click_value STRING,
  _created_at_epoch_seconds FLOAT64,
  _created_at_nanosecond FLOAT64
>
LANGUAGE js AS r"""
return (function () {
/*
 * Shared channel classifier. Keep this module dependency-free: build-artifacts.mjs
 * copies the declarations into a BigQuery JavaScript UDF.
 */
const TAXONOMY_VERSION = '0.1.0';
const CHANNELS = [
  'Paid Search', 'Paid Social', 'Paid Other', 'Organic Search',
  'Organic Social', 'Email', 'SMS', 'Direct', 'Referral', 'Affiliate', 'Other'
];

const SEARCH_SOURCES = new Set([
  'google', 'googleads', 'google ads', 'bing', 'bingads', 'microsoft', 'yahoo',
  'duckduckgo', 'baidu', 'yandex', 'ecosia', 'brave', 'ask'
]);
const SOCIAL_SOURCES = new Set([
  'facebook', 'facebook.com', 'instagram', 'instagram.com', 'linkedin',
  'linkedin.com', 'twitter', 'x', 'x.com', 'tiktok', 'tiktok.com', 'reddit',
  'reddit.com', 'pinterest', 'pinterest.com', 'snapchat', 'youtube', 'youtube.com', 'meta', 'ig'
]);
const PAID_SOCIAL_NETWORKS = new Set([
  'facebook_ads', 'linkedin_ads', 'reddit_ads', 'reddit', 'pinterest_ads',
  'paid_social', 'tiktok_ads', 'tiktok'
]);
const PAID_SEARCH_NETWORKS = new Set(['google_ads', 'google_ads_pmax', 'bingads', 'paid_search']);
const PAID_OTHER_NETWORKS = new Set(['criteo', 'stackadapt', 'stackadapt_ads']);
const AFFILIATE_SOURCES = new Set(['cj', 'rakuten', 'impact', 'shareasale', 'awin', 'partnerize']);
const EMAIL_SOURCES = new Set(['mailchimp', 'klaviyo', 'hubspot', 'customer.io', 'iterable', 'sendgrid', 'braze', 'newsletter', 'email', 'e-mail']);
const SMS_SOURCES = new Set(['attentive', 'postscript', 'klaviyo_sms', 'sms']);
const SEARCH_HOSTS = new Set(['google.com', 'bing.com', 'yahoo.com', 'duckduckgo.com', 'baidu.com', 'yandex.com', 'yandex.ru', 'ecosia.org', 'search.brave.com', 'ask.com', 'aol.com']);
const SOCIAL_HOSTS = new Set(['facebook.com', 'instagram.com', 'linkedin.com', 'twitter.com', 'x.com', 'tiktok.com', 'reddit.com', 'pinterest.com', 'snapchat.com', 'youtube.com', 't.co']);

function text(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function lower(value) { return text(decode(value)).toLowerCase(); }

function decode(value) {
  let result = text(value);
  for (let pass = 0; pass < 5; pass += 1) {
    let decoded;
    try { decoded = decodeURIComponent(result); } catch (error) { break; }
    if (decoded === result) break;
    result = decoded;
  }
  return result;
}

function validClickId(value) {
  const candidate = text(decode(value));
  if (!candidate || /^(?:null|undefined|\[object object\])$/i.test(candidate)) return '';
  return candidate;
}

function clickValue(clickIds, name) {
  if (!clickIds || typeof clickIds !== 'object') return '';
  if (Array.isArray(clickIds)) {
    for (let i = 0; i < clickIds.length; i += 1) {
      if (clickIds[i] && lower(clickIds[i].name) === name) {
        const candidate = validClickId(clickIds[i].value);
        if (candidate) return candidate;
      }
    }
    return '';
  }
  return validClickId(clickIds[name]);
}

function queryParams(url) {
  const result = {};
  const raw = text(url).split('#')[0];
  if (!raw) return result;
  const queryStart = raw.indexOf('?');
  if (queryStart < 0) return result;
  let query = raw.slice(queryStart + 1);
  const hashStart = query.indexOf('#');
  if (hashStart >= 0) query = query.slice(0, hashStart);
  query.split('&').forEach((part) => {
    if (!part) return;
    const equals = part.indexOf('=');
    const rawKey = equals < 0 ? part : part.slice(0, equals);
    const rawValue = equals < 0 ? '' : part.slice(equals + 1);
    const key = lower(rawKey.replace(/\+/g, ' '));
    if (key && result[key] === undefined) result[key] = rawValue.replace(/\+/g, ' ');
  });
  return result;
}

function hostOf(value) {
  const raw = text(value);
  if (!raw || /\s|[\\<>]/.test(raw)) return '';
  const match = raw.match(/^(?:https?:)?\/\/([^/?#]+)(?:[/?#]|$)/i);
  if (!match) return '';
  const authority = match[1].slice(match[1].lastIndexOf('@') + 1).toLowerCase();
  const parts = authority.match(/^([^:]+)(?::([0-9]+))?$/);
  if (!parts || (parts[2] && Number(parts[2]) > 65535)) return '';
  const host = parts[1].replace(/\.$/, '');
  if (host.length > 253 || !host.split('.').every((label) => /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(label))) return '';
  return host;
}

function hostMatches(host, base) { return host === base || host.endsWith(`.${base}`); }

function sameHost(a, b) {
  const left = hostOf(a); const right = hostOf(b);
  return Boolean(left && right && (hostMatches(left, right) || hostMatches(right, left)));
}

function sourceHostHint(source) {
  // Inputs to this helper are already normalized; do not decode a second time.
  const value = text(source);
  const host = hostOf(value) || (/^[a-z0-9.-]+$/.test(value) ? hostOf(`https://${value}`) : '');
  const googleHosts = ['google.com', 'google.co.uk', 'google.ca', 'google.com.au', 'google.au', 'google.de', 'google.fr', 'google.es', 'google.it', 'google.nl', 'google.ie', 'google.co.nz', 'google.nz', 'google.co.in', 'google.in', 'google.sg', 'google.com.sg', 'google.co.jp'];
  if (SEARCH_SOURCES.has(value) || [...SEARCH_HOSTS, ...googleHosts].some((base) => hostMatches(host, base))) return 'Paid Search';
  if (SOCIAL_SOURCES.has(value) || [...SOCIAL_HOSTS].some((base) => hostMatches(host, base))) return 'Paid Social';
  return '';
}

function normalizeChannelLabel(value) {
  const label = lower(value).replace(/[_-]+/g, ' ').replace(/\s+/g, ' ');
  if (!label || label === '(not set)' || label === 'not set' || label === 'unassigned' || label === 'unknown' || label === 'mobile push') return 'Other';
  if (label === 'affiliates' || label === 'affiliate') return 'Affiliate';
  if (label === 'display' || label === 'paid shopping' || label === 'cross network' || label === 'cross-network' || label === 'paid video' || label === 'paid audio' || label === 'audio') return 'Paid Other';
  if (label === 'organic video') return 'Organic Social';
  if (label === 'organic shopping') return 'Organic Search';
  if (label === 'ai assistant') return 'Referral';
  const direct = { 'paid search': 'Paid Search', 'paid social': 'Paid Social', 'paid other': 'Paid Other', 'organic search': 'Organic Search', 'organic social': 'Organic Social', email: 'Email', sms: 'SMS', direct: 'Direct', referral: 'Referral', other: 'Other' };
  return direct[label] || 'Other';
}

// Select the original encoded tracking values without decoding them for storage.
// Validation uses the same helpers as classification; callers still classify the
// original input once, rather than feeding this projection back to the classifier.
function extractRawTrackingEvidence(input) {
  const value = input && typeof input === 'object' ? input : {};
  const params = hostOf(value.landing_url) ? queryParams(value.landing_url) : {};
  const result = {};
  for (const field of ['utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term']) {
    result[field] = text(value[field]) ? value[field] : text(params[field]) ? params[field] : null;
  }
  const clickNames = ['dclid', 'gclid', 'gbraid', 'wbraid', 'msclkid', 'fbclid', 'ttclid', 'rdt_cid', 'li_fat_id', 'twclid', 'epik', 'sccid', 'srsltid'];
  result.click_ids = {};
  for (const name of clickNames) {
    let raw = null;
    const clicks = value.click_ids;
    if (Array.isArray(clicks)) {
      for (const entry of clicks) {
        if (entry && lower(entry.name) === name && validClickId(entry.value)) { raw = entry.value; break; }
      }
    } else if (clicks && typeof clicks === 'object' && validClickId(clicks[name])) raw = clicks[name];
    result.click_ids[name] = raw !== null ? raw : validClickId(params[name]) ? params[name] : null;
  }
  return result;
}

function classify(input) {
  const value = input && typeof input === 'object' ? input : {};
  const landing = text(value.landing_url);
  const landingValid = Boolean(hostOf(landing));
  const landingParams = landingValid ? queryParams(landing) : {};
  const source = lower(text(value.utm_source) ? value.utm_source : landingParams.utm_source);
  const medium = lower(text(value.utm_medium) ? value.utm_medium : landingParams.utm_medium);
  const mediumKey = medium.replace(/[_-]+/g, ' ').replace(/\s+/g, ' ');
  const native = normalizeChannelLabel(value.native_channel);
  const clicks = value.click_ids;
  const ids = {
    dclid: clickValue(clicks, 'dclid') || validClickId(landingParams.dclid),
    gclid: clickValue(clicks, 'gclid') || validClickId(landingParams.gclid),
    gbraid: clickValue(clicks, 'gbraid') || validClickId(landingParams.gbraid),
    wbraid: clickValue(clicks, 'wbraid') || validClickId(landingParams.wbraid),
    msclkid: clickValue(clicks, 'msclkid') || validClickId(landingParams.msclkid),
    fbclid: clickValue(clicks, 'fbclid') || validClickId(landingParams.fbclid),
    ttclid: clickValue(clicks, 'ttclid') || validClickId(landingParams.ttclid),
    rdt_cid: clickValue(clicks, 'rdt_cid') || validClickId(landingParams.rdt_cid),
    li_fat_id: clickValue(clicks, 'li_fat_id') || validClickId(landingParams.li_fat_id),
    twclid: clickValue(clicks, 'twclid') || validClickId(landingParams.twclid),
    epik: clickValue(clicks, 'epik') || validClickId(landingParams.epik),
    sccid: clickValue(clicks, 'sccid') || validClickId(landingParams.sccid)
  };
  // srsltid is intentionally retained only as raw input; it never establishes paid traffic.
  const has = (name) => Boolean(ids[name]);
  if (has('dclid')) return { channel: 'Paid Other', rule_id: 'click_id_dclid', taxonomy_version: TAXONOMY_VERSION };
  if (has('gclid') || has('gbraid') || has('wbraid') || has('msclkid')) return { channel: 'Paid Search', rule_id: 'click_id_search', taxonomy_version: TAXONOMY_VERSION };
  if (has('fbclid') || has('ttclid') || has('rdt_cid') || has('li_fat_id') || has('twclid') || has('epik') || has('sccid')) return { channel: 'Paid Social', rule_id: 'click_id_social', taxonomy_version: TAXONOMY_VERSION };

  const network = lower(value.network_id);
  if (PAID_SEARCH_NETWORKS.has(network)) return { channel: 'Paid Search', rule_id: 'network_paid_search', taxonomy_version: TAXONOMY_VERSION };
  if (PAID_SOCIAL_NETWORKS.has(network) || network.indexOf('tiktok_') === 0) return { channel: 'Paid Social', rule_id: 'network_paid_social', taxonomy_version: TAXONOMY_VERSION };
  if (PAID_OTHER_NETWORKS.has(network)) return { channel: 'Paid Other', rule_id: 'network_paid_other', taxonomy_version: TAXONOMY_VERSION };
  if (network === 'affiliate' || AFFILIATE_SOURCES.has(network)) return { channel: 'Affiliate', rule_id: 'network_affiliate', taxonomy_version: TAXONOMY_VERSION };

  // Explicit paid categories win over a conflicting platform source.
  if (mediumKey === 'paid search') return { channel: 'Paid Search', rule_id: 'paid_medium_search', taxonomy_version: TAXONOMY_VERSION };
  if (mediumKey === 'paid social') return { channel: 'Paid Social', rule_id: 'paid_medium_social', taxonomy_version: TAXONOMY_VERSION };
  if (/^(display|banner|cpm|native|video|audio|paid other|paid video|paid audio|paidvideo)$/.test(mediumKey)) return { channel: 'Paid Other', rule_id: 'paid_medium_other', taxonomy_version: TAXONOMY_VERSION };
  if (/^(paid(?: .+)?|cpc|cpa|cpv|cpe|cpp|ppc|sem|retargeting|remarketing)$/.test(mediumKey)) {
    const hint = sourceHostHint(source);
    return { channel: hint || 'Paid Other', rule_id: hint === 'Paid Search' ? 'paid_medium_search' : hint === 'Paid Social' ? 'paid_medium_social' : 'paid_medium_other', taxonomy_version: TAXONOMY_VERSION };
  }

  if (native !== 'Direct' && native !== 'Other') return { channel: native, rule_id: 'native_channel', taxonomy_version: TAXONOMY_VERSION };
  if (/^(email|e-mail|newsletter)$/i.test(medium)) return { channel: 'Email', rule_id: 'medium_email', taxonomy_version: TAXONOMY_VERSION };
  if (/^(sms|text|text_message)$/i.test(medium)) return { channel: 'SMS', rule_id: 'medium_sms', taxonomy_version: TAXONOMY_VERSION };
  if (/^(affiliate|affiliates)$/i.test(medium)) return { channel: 'Affiliate', rule_id: 'medium_affiliate', taxonomy_version: TAXONOMY_VERSION };
  if (/^(organic|seo)$/i.test(medium) && (sourceHostHint(source) === 'Paid Search' || SEARCH_SOURCES.has(source))) return { channel: 'Organic Search', rule_id: 'medium_organic_search', taxonomy_version: TAXONOMY_VERSION };
  if (/^(social|social-network|social_media|organic_social)$/i.test(medium) || (medium === 'organic' && (sourceHostHint(source) === 'Paid Social' || SOCIAL_SOURCES.has(source)))) return { channel: 'Organic Social', rule_id: 'medium_organic_social', taxonomy_version: TAXONOMY_VERSION };
  if (/^(organic|seo)$/i.test(medium)) return { channel: 'Organic Search', rule_id: 'medium_organic_search', taxonomy_version: TAXONOMY_VERSION };
  if (/^(referral|refer)$/i.test(medium)) return { channel: 'Referral', rule_id: 'medium_referral', taxonomy_version: TAXONOMY_VERSION };

  const shopifyType = lower(value.shopify_source_type);
  const shopifySource = lower(value.shopify_source);
  if (shopifyType === 'email') return { channel: 'Email', rule_id: 'shopify_email', taxonomy_version: TAXONOMY_VERSION };
  if (shopifyType === 'sms') return { channel: 'SMS', rule_id: 'shopify_sms', taxonomy_version: TAXONOMY_VERSION };
  if (shopifyType === 'affiliate') return { channel: 'Affiliate', rule_id: 'shopify_affiliate', taxonomy_version: TAXONOMY_VERSION };
  if (shopifyType === 'search') return { channel: 'Organic Search', rule_id: 'shopify_search', taxonomy_version: TAXONOMY_VERSION };
  if (shopifyType === 'social') return { channel: 'Organic Social', rule_id: 'shopify_social', taxonomy_version: TAXONOMY_VERSION };
  if (shopifyType === 'ad' || shopifyType === 'retargeting') {
    const platformHint = sourceHostHint(shopifySource);
    if (platformHint === 'Paid Search') return { channel: 'Paid Search', rule_id: 'shopify_paid_search_platform', taxonomy_version: TAXONOMY_VERSION };
    if (platformHint === 'Paid Social') return { channel: 'Paid Social', rule_id: 'shopify_paid_social_platform', taxonomy_version: TAXONOMY_VERSION };
    return { channel: 'Paid Other', rule_id: 'shopify_paid_without_platform', taxonomy_version: TAXONOMY_VERSION };
  }
  if (shopifyType === 'seo' || shopifyType === 'organic') return { channel: 'Organic Search', rule_id: 'shopify_organic_search', taxonomy_version: TAXONOMY_VERSION };
  if (shopifyType === 'post') return { channel: 'Organic Social', rule_id: 'shopify_social', taxonomy_version: TAXONOMY_VERSION };
  if (shopifyType === 'newsletter') return { channel: 'Email', rule_id: 'shopify_email', taxonomy_version: TAXONOMY_VERSION };
  if (shopifyType === 'referral') return { channel: 'Referral', rule_id: 'shopify_referral', taxonomy_version: TAXONOMY_VERSION };
  // Unknown Shopify types are nonterminal; source and referrer evidence still apply.
  for (const hintSource of [source, shopifySource]) {
    if (EMAIL_SOURCES.has(hintSource)) return { channel: 'Email', rule_id: 'source_email', taxonomy_version: TAXONOMY_VERSION };
    if (SMS_SOURCES.has(hintSource)) return { channel: 'SMS', rule_id: 'source_sms', taxonomy_version: TAXONOMY_VERSION };
    if (AFFILIATE_SOURCES.has(hintSource)) return { channel: 'Affiliate', rule_id: 'source_affiliate', taxonomy_version: TAXONOMY_VERSION };
    if (sourceHostHint(hintSource) === 'Paid Search') return { channel: 'Organic Search', rule_id: 'source_search_hint', taxonomy_version: TAXONOMY_VERSION };
    if (sourceHostHint(hintSource) === 'Paid Social') return { channel: 'Organic Social', rule_id: 'source_social_hint', taxonomy_version: TAXONOMY_VERSION };
  }

  const referrer = text(value.referrer);
  if (referrer && hostOf(referrer) && (!landingValid || !sameHost(referrer, landing))) {
    const referrerHost = hostOf(referrer);
    const referrerHint = sourceHostHint(referrerHost);
    if (referrerHint === 'Paid Search') return { channel: 'Organic Search', rule_id: 'referrer_search', taxonomy_version: TAXONOMY_VERSION };
    if (referrerHint === 'Paid Social') return { channel: 'Organic Social', rule_id: 'referrer_social', taxonomy_version: TAXONOMY_VERSION };
    return { channel: 'Referral', rule_id: 'external_referrer', taxonomy_version: TAXONOMY_VERSION };
  }
  if (native === 'Direct' || shopifyType === 'direct' || (source === '(direct)' && (medium === '(none)' || medium === '(not set)'))) return { channel: 'Direct', rule_id: 'explicit_direct', taxonomy_version: TAXONOMY_VERSION };
  const unknownSignal = network || shopifyType || shopifySource || lower(value.native_channel) || lower(value.utm_campaign) || lower(landingParams.utm_campaign);
  if (landingValid && !source && !medium && !unknownSignal && (!referrer || (hostOf(referrer) && sameHost(referrer, landing)))) return { channel: 'Direct', rule_id: 'inferred_direct', taxonomy_version: TAXONOMY_VERSION };
  return { channel: 'Other', rule_id: 'fallback_other', taxonomy_version: TAXONOMY_VERSION };
}

function classifyChannel(input) { return classify(input).channel; }

const CLICK_ORDER = [
  ['dclid', 'google_display'], ['gclid', 'google_ads'], ['gbraid', 'google_ads'],
  ['wbraid', 'google_ads'], ['msclkid', 'bingads'], ['fbclid', 'facebook_ads'],
  ['ttclid', 'tiktok_ads'], ['rdt_cid', 'reddit_ads'], ['li_fat_id', 'linkedin_ads'],
  ['twclid', 'twitter_ads'], ['epik', 'pinterest_ads'], ['sccid', 'snapchat_ads']
];
const UTM_KEYS = ['utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term'];
const CLICK_KEYS = [...CLICK_ORDER.map(([field]) => field), 'srsltid'];
function stringValue(value) { return typeof value === 'string' ? value.trim() : ''; }
function requireText(value, label) {
  if (typeof value !== 'string' || !value.trim()) throw new TypeError(`${label} must be a nonempty string`);
  return value.trim();
}
function requireIdentity(value, label) {
  const text = requireText(value, label);
  if (text !== value) throw new TypeError(`${label} cannot have surrounding whitespace`);
  return value;
}
function optionalText(value, label) {
  return value === undefined || value === null ? null : requireText(value, label);
}
function decodeOpaque(value) {
  let result = stringValue(value);
  for (let pass = 0; pass < 5; pass += 1) {
    let decoded;
    try { decoded = decodeURIComponent(result); } catch { break; }
    if (decoded === result) break;
    result = decoded;
  }
  return result.trim();
}
function normalizeUtm(value) { return decodeOpaque(value).replaceAll('+', ' ').trim().toLowerCase(); }
function cleanClick(value) {
  const decoded = decodeOpaque(value);
  return !decoded || /^(?:null|undefined|\[object object\])$/i.test(decoded) ? '' : decoded;
}
function normalizeUtmSet(value) {
  return Object.fromEntries(UTM_KEYS.map((key) => [key, normalizeUtm(value?.[key])]));
}
function hasUtm(utm) { return UTM_KEYS.some((key) => Boolean(utm[key])); }
function rawValues(source, keys) {
  return Object.fromEntries(keys.map((key) => [key, typeof source?.[key] === 'string' ? source[key] : null]));
}
function rawTracking(lead) {
  return { click_ids: rawValues(lead.click_ids, CLICK_KEYS), current_utm: rawValues(lead, UTM_KEYS), first_touch_utm: rawValues(lead.first_touch, UTM_KEYS), first_touch_click_ids: rawValues(lead.first_touch?.click_ids, CLICK_KEYS), native_channel: typeof lead.native_channel === 'string' ? lead.native_channel : null };
}
function arrayOption(options, key) {
  if (options[key] === undefined) return [];
  if (!Array.isArray(options[key])) throw new TypeError(`${key} must be an array`);
  return options[key];
}
function mappingMetadata(row, label) {
  if (!row || typeof row !== 'object' || Array.isArray(row)) throw new TypeError(`${label} must be an object`);
  if (!CHANNELS.includes(row.channel)) throw new TypeError(`${label}.channel must be a canonical channel`);
  return { channel: row.channel, network_id: row.network_id === undefined || row.network_id === null ? null : requireIdentity(row.network_id, `${label}.network_id`), campaign_key: optionalText(row.campaign_key, `${label}.campaign_key`) };
}
function addUnique(map, key, value, label) {
  if (map.has(key) && JSON.stringify(map.get(key)) !== JSON.stringify(value)) throw new TypeError(`conflicting ${label}`);
  map.set(key, value);
}
function compileConfig(sourceMap = [], sourcePatterns = []) {
  const exact = new Map(); const patterns = new Map();
  for (const row of sourceMap) {
    const metadata = mappingMetadata(row, 'source_map');
    const source = normalizeUtm(requireText(row.utm_source ?? row.source, 'source_map.source'));
    const mediumRaw = row.utm_medium ?? row.medium;
    if (mediumRaw !== undefined && mediumRaw !== null && typeof mediumRaw !== 'string') throw new TypeError('source_map.medium must be a string');
    const medium = normalizeUtm(mediumRaw);
    if (!source) throw new TypeError('source_map.source must normalize to a nonempty string');
    addUnique(exact, JSON.stringify([source, medium]), { source, medium, ...metadata }, 'source_map entries');
  }
  for (const row of sourcePatterns) {
    const metadata = mappingMetadata(row, 'source_patterns');
    const id = requireText(row.id, 'source_patterns.id');
    if (typeof row.priority !== 'number' || !Number.isFinite(row.priority)) throw new TypeError('source_patterns.priority must be a finite number');
    const source = requireText(row.source_regex, 'source_patterns.source_regex');
    const medium = optionalText(row.medium_regex, 'source_patterns.medium_regex');
    try { new RegExp(source, 'i'); if (medium) new RegExp(medium, 'i'); } catch { throw new TypeError('invalid source pattern regex'); }
    addUnique(patterns, id, { id, priority: row.priority, source, medium, ...metadata }, 'source_patterns IDs');
  }
  return { exact: [...exact.values()], patterns: [...patterns.values()].sort((a, b) => a.priority - b.priority || compareText(a.id, b.id)).map((row) => ({ ...row, sourceRegex: new RegExp(row.source, 'i'), mediumRegex: row.medium ? new RegExp(row.medium, 'i') : null })) };
}
function sourceMatch(utm, config) {
  const exact = config.exact.filter((row) => row.source === utm.utm_source && (!row.medium || row.medium === utm.utm_medium)).sort((a, b) => Number(Boolean(b.medium)) - Number(Boolean(a.medium)));
  return exact[0] ?? config.patterns.find((row) => row.sourceRegex.test(utm.utm_source) && (!row.mediumRegex || row.mediumRegex.test(utm.utm_medium))) ?? null;
}
function resolveUtm(utm, config, rawUtm) {
  const mapping = sourceMatch(utm, config);
  // The canonical classifier receives raw evidence and owns its five decoding passes.
  const classification = mapping ? classify({ native_channel: mapping.channel }) : classify(Object.fromEntries(UTM_KEYS.map((key) => [key, rawUtm?.[key]])));
  return { classification, network_id: mapping?.network_id ?? '', campaign_key: mapping?.campaign_key ?? '', known: Boolean(mapping) || classification.rule_id !== 'fallback_other' };
}
function selectedClick(raw, selected, prefix) {
  for (const [field, network_id] of CLICK_ORDER) {
    const matchValue = cleanClick(raw?.click_ids?.[field]);
    if (!matchValue) continue;
    const classification = classify({ click_ids: { [field]: raw.click_ids[field] } });
    return { classification, channel: classification.channel, basisKey: `${prefix}:${field}`, matchKey: field, matchValue, network_id, campaign_key: '', selected, selected_raw: raw, quality_status: 'matched', confidence: prefix === 'click' ? 'HIGH' : 'LOW' };
  }
  return null;
}
function resolveAttribution(lead, config) {
  const current = normalizeUtmSet(lead); const first = normalizeUtmSet(lead.first_touch);
  const click = selectedClick(lead, current, 'click');
  if (click) return click;
  if (hasUtm(current)) {
    const resolved = resolveUtm(current, config, lead);
    return { ...resolved, channel: resolved.classification.channel, basisKey: 'utm:current', matchKey: 'utm_source', matchValue: current.utm_source || current.utm_medium, selected: current, selected_raw: lead, quality_status: resolved.known ? 'matched' : 'unmapped', confidence: resolved.known ? 'MEDIUM' : 'UNMATCHED' };
  }
  const firstClick = selectedClick(lead.first_touch, first, 'first_touch_click');
  if (firstClick) return firstClick;
  if (hasUtm(first)) {
    const resolved = resolveUtm(first, config, lead.first_touch);
    return { ...resolved, channel: resolved.classification.channel, basisKey: 'utm:first_touch', matchKey: 'first_touch_utm_source', matchValue: first.utm_source || first.utm_medium, selected: first, selected_raw: lead.first_touch, quality_status: resolved.known ? 'matched' : 'unmapped', confidence: resolved.known ? 'LOW' : 'UNMATCHED' };
  }
  return { classification: classify({}), channel: 'Other', basisKey: 'none', matchKey: 'none', matchValue: '', network_id: '', campaign_key: '', selected: current, selected_raw: lead, quality_status: 'unattributed', confidence: 'UNMATCHED' };
}
function prepareAds(options) {
  const entities = new Map();
  for (const row of arrayOption(options, 'ad_catalog')) {
    const entity = {};
    for (const key of ['source_system', 'source_scope', 'network_id', 'ad_key']) entity[key] = key === 'ad_key' ? requireText(row?.[key], `ad_catalog.${key}`) : requireIdentity(row?.[key], `ad_catalog.${key}`);
    entity.campaign_key = optionalText(row.campaign_key, 'ad_catalog.campaign_key');
    entity.ad_name = optionalText(row.ad_name, 'ad_catalog.ad_name');
    const key = JSON.stringify([entity.source_system, entity.source_scope, entity.network_id, entity.ad_key]);
    addUnique(entities, key, entity, 'ad_catalog entity metadata');
  }
  const bindings = arrayOption(options, 'ad_scope_bindings').map((row) => Object.fromEntries(['crm_source_system', 'crm_source_scope', 'ad_source_system', 'ad_source_scope', 'platform', 'entity_type'].map((key) => [key, requireIdentity(row?.[key], `ad_scope_bindings.${key}`)])));
  return { catalog: [...entities.values()], bindings };
}
function candidateIdentity(row) {
  return { source_system: row.source_system, source_scope: row.source_scope, ad_key: row.ad_key, campaign_key: row.campaign_key };
}
function compareText(a, b) { return a < b ? -1 : a > b ? 1 : 0; }
function sortedCandidates(rows) {
  return rows.map(candidateIdentity).sort((a, b) => compareText(JSON.stringify([a.source_system, a.source_scope, a.ad_key, a.campaign_key]), JSON.stringify([b.source_system, b.source_scope, b.ad_key, b.campaign_key])));
}
function adResult(rows = [], method = 'none', scopeMethod = 'none', confidence = 'UNMATCHED') {
  const candidates = sortedCandidates(rows); const match = method === 'exact_ad_key' || method === 'normalized_ad_name' ? candidates[0] : null;
  return { ad_source_system: match?.source_system ?? null, ad_source_scope: match?.source_scope ?? null, ad_key: match?.ad_key ?? null, campaign_key: match?.campaign_key ?? null, ad_match_method: method, ad_scope_method: scopeMethod, ad_confidence: confidence, ad_match_status: match ? 'matched' : method === 'ambiguous' ? 'ambiguous' : 'unmatched', candidate_ads: candidates, candidate_ad_keys: candidates.map((row) => `${row.source_system}:${row.source_scope}:${row.ad_key}`) };
}
function adMatch(lead, attribution, ads) {
  const network = attribution.network_id;
  const rawContent = attribution.selected_raw?.utm_content;
  const contentId = decodeOpaque(rawContent); const contentName = normalizeUtm(rawContent);
  if (!network || !contentId) return adResult();
  let candidates = ads.catalog.filter((row) => row.network_id === network);
  let scopeMethod;
  if (ads.bindings.length) {
    const allowed = ads.bindings.filter((row) => row.crm_source_system === lead.source_system && row.crm_source_scope === lead.source_scope && row.platform === network && row.entity_type === 'ad');
    if (!allowed.length) return adResult([], 'none', 'binding_not_authorized');
    scopeMethod = 'explicit_binding';
    candidates = candidates.filter((row) => allowed.some((binding) => row.source_system === binding.ad_source_system && row.source_scope === binding.ad_source_scope));
  } else {
    const scopes = new Set(candidates.map((row) => JSON.stringify([row.source_system, row.source_scope])));
    if (scopes.size > 1) return adResult(candidates, 'ambiguous', 'multiple_accounts');
    scopeMethod = scopes.size ? 'single_account_inference' : 'none';
  }
  const exact = candidates.filter((row) => decodeOpaque(row.ad_key) === contentId);
  if (exact.length === 1) return adResult(exact, 'exact_ad_key', scopeMethod, 'HIGH');
  if (exact.length > 1) return adResult(exact, 'ambiguous', scopeMethod);
  // Normalize each original raw name exactly once; never normalize contentId again.
  const names = contentName ? candidates.filter((row) => row.ad_name && normalizeUtm(row.ad_name) === contentName) : [];
  if (names.length === 1) return adResult(names, 'normalized_ad_name', scopeMethod, 'MEDIUM');
  if (names.length > 1) return adResult(names, 'ambiguous', scopeMethod);
  return adResult([], 'none', scopeMethod);
}
function dateRank(value) {
  if (value === null) return null;
  const m = typeof value === 'string' && /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/.exec(value);
  if (!m) throw new TypeError('created_at must be a valid calendar ISO timestamp with offset/Z or null');
  const [year, month, day, hour, minute, second] = m.slice(1, 7).map(Number);
  const leap = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
  const days = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  if (month < 1 || month > 12 || day < 1 || day > days[month - 1] || hour > 23 || minute > 59 || second > 59 || (m[7] !== 'Z' && (Number(m[7].slice(1, 3)) > 23 || Number(m[7].slice(4)) > 59)) || !Number.isFinite(Date.parse(value))) throw new TypeError('created_at must be a valid calendar ISO timestamp with offset/Z or null');
  // Parse a whole second before applying the fraction, including before the epoch.
  const epoch_seconds = Date.parse(value.replace(/\.\d+(?=Z|[+-]\d{2}:\d{2}$)/, '')) / 1000;
  const fraction = /\.(\d{1,9})(?=Z|[+-]\d{2}:\d{2}$)/.exec(value)?.[1] ?? '';
  return { epoch_seconds, nanosecond: Number(fraction.padEnd(9, '0')) };
}
function compareDates(left, right) {
  if (left === null) return right === null ? 0 : 1;
  if (right === null) return -1;
  return left.epoch_seconds - right.epoch_seconds || left.nanosecond - right.nanosecond;
}
function attributeLeads(leads, options = {}) {
  if (!Array.isArray(leads)) throw new TypeError('leads must be an array');
  if (!options || typeof options !== 'object' || Array.isArray(options)) throw new TypeError('options must be an object');
  const config = compileConfig(arrayOption(options, 'source_map'), arrayOption(options, 'source_patterns'));
  const ads = prepareAds(options); const seenKeys = new Set();
  const prepared = leads.map((lead) => {
    if (!lead || typeof lead !== 'object' || Array.isArray(lead)) throw new TypeError('lead must be an object');
    for (const field of ['source_system', 'source_scope', 'lead_key']) {
      requireIdentity(lead[field], `lead.${field}`);
    }
    const rank = dateRank(lead.created_at);
    const key = JSON.stringify([lead.source_system, lead.source_scope, lead.lead_key]);
    if (seenKeys.has(key)) throw new TypeError('duplicate lead key');
    seenKeys.add(key);
    const attribution = resolveAttribution(lead, config);
    const matchedAds = adMatch(lead, attribution, ads);
    const dedupKey = ['click:', 'first_touch_click:'].some((prefix) => attribution.basisKey.startsWith(prefix)) ? JSON.stringify([lead.source_system, lead.source_scope, attribution.matchKey, attribution.matchValue]) : null;
    return { lead, attribution, ads: matchedAds, dedupKey, rank };
  });
  const primaries = new Map();
  for (const item of prepared) {
    if (!item.dedupKey) continue;
    const previous = primaries.get(item.dedupKey);
    if (!previous || compareDates(item.rank, previous.rank) < 0 || (compareDates(item.rank, previous.rank) === 0 && compareText(item.lead.lead_key, previous.lead.lead_key) < 0)) primaries.set(item.dedupKey, item);
  }
  return prepared.map((item) => {
    const { lead, attribution, ads, dedupKey } = item;
    return { source_system: lead.source_system, source_scope: lead.source_scope, lead_key: lead.lead_key, created_at: lead.created_at, channel: attribution.classification.channel, taxonomy_version: TAXONOMY_VERSION, rule: attribution.classification.rule_id, attribution_basis: 'crm_paid_resolution', match_key: attribution.matchKey, confidence: attribution.confidence, quality_status: attribution.quality_status, raw_evidence: rawTracking(lead), is_attribution_primary: dedupKey ? primaries.get(dedupKey) === item : true, ...ads, network_id: attribution.network_id || null, campaign_key: ads.campaign_key ?? (attribution.campaign_key || null) };
  });
}

const options = JSON.parse(options_json);
// A null lead validates configuration even when the CRM population is empty.
if (lead_json === null) { attributeLeads([], options); return null; }
const lead = JSON.parse(lead_json);
const result = attributeLeads([lead], options)[0];
const selected = resolveAttribution(lead, compileConfig(arrayOption(options, 'source_map'), arrayOption(options, 'source_patterns')));
const isClick = selected.basisKey.startsWith('click:') || selected.basisKey.startsWith('first_touch_click:');
const timestamp = dateRank(lead.created_at);
return Object.assign({}, result, {
  _selected_click_value: isClick ? selected.matchValue : null,
  _created_at_epoch_seconds: timestamp === null ? null : timestamp.epoch_seconds,
  _created_at_nanosecond: timestamp === null ? null : timestamp.nanosecond
});
})();
""";

-- Replace only these input CTEs with explicitly scoped warehouse inputs.
CREATE TEMP TABLE crm_configuration AS
WITH configuration_input AS (SELECT '{"source_map":[],"source_patterns":[],"ad_catalog":[{"source_system":"synthetic_ads","source_scope":"synthetic_ad_account","network_id":"google_ads","ad_key":"DemoAd+Case","campaign_key":"DemoCampaign+Case","ad_name":"Demo Campaign"}],"ad_scope_bindings":[{"crm_source_system":"synthetic_crm","crm_source_scope":"synthetic_crm_scope","ad_source_system":"synthetic_ads","ad_source_scope":"synthetic_ad_account","platform":"google_ads","entity_type":"ad"}]}' AS options_json)
SELECT options_json FROM configuration_input;
CREATE TEMP TABLE crm_lead_input AS
WITH lead_input AS (
SELECT 0 AS input_position, '{"source_system":"synthetic_crm","source_scope":"synthetic_crm_scope","created_at":"2026-01-02T00:00:00Z","click_ids":{"gclid":"Shared+DemoClick"},"utm_content":"DemoAd+Case","lead_key":"demo-first"}' AS lead_json
UNION ALL
SELECT 1 AS input_position, '{"source_system":"synthetic_crm","source_scope":"synthetic_crm_scope","created_at":"2026-01-03T00:00:00Z","click_ids":{"gclid":"Shared+DemoClick"},"utm_content":"DemoAd+Case","lead_key":"demo-later"}' AS lead_json
UNION ALL
SELECT 2 AS input_position, '{"source_system":"synthetic_crm","source_scope":"synthetic_crm_scope","lead_key":"demo-email","created_at":null,"utm_source":"unknown.example","utm_medium":"email"}' AS lead_json
)
SELECT input_position, lead_json FROM lead_input;

ASSERT (SELECT COUNT(*) = 1 FROM crm_configuration)
AS 'exactly one configuration row is required';

-- Validate options even for an empty lead input; every configuration is executed.
ASSERT (SELECT COALESCE(LOGICAL_AND(resolve_crm_lead(NULL, options_json) IS NULL), TRUE)
        FROM crm_configuration) AS 'invalid CRM attribution configuration';

CREATE TEMP TABLE crm_resolved AS
SELECT i.input_position,
       resolve_crm_lead(i.lead_json, c.options_json) AS resolved
FROM crm_lead_input AS i
CROSS JOIN crm_configuration AS c;

-- This check is global within the complete input population, before ROW_NUMBER.
ASSERT NOT EXISTS (
  SELECT 1 FROM crm_resolved
  GROUP BY resolved.source_system, resolved.source_scope, resolved.lead_key
  HAVING COUNT(*) > 1
) AS 'duplicate lead key';

WITH resolved_rows AS (
  SELECT input_position,
         resolved.* EXCEPT (is_attribution_primary, _selected_click_value, _created_at_epoch_seconds, _created_at_nanosecond),
         IF(resolved._selected_click_value IS NULL, TRUE,
            ROW_NUMBER() OVER (
              PARTITION BY resolved.source_system, resolved.source_scope,
                           resolved.match_key, resolved._selected_click_value
              ORDER BY resolved._created_at_epoch_seconds ASC NULLS LAST,
                       resolved._created_at_nanosecond ASC NULLS LAST, resolved.lead_key ASC
            ) = 1) AS is_attribution_primary
  FROM crm_resolved
)
SELECT * EXCEPT (input_position)
FROM resolved_rows
ORDER BY input_position;
