-- Native BigQuery Standard SQL. Temporary synthetic inputs only.
-- BEGIN REPLACEABLE INPUTS
CREATE OR REPLACE TEMP TABLE configuration_input AS
SELECT CAST('synthetic-check' AS STRING) AS invocation_key, CAST('synthetic-window' AS STRING) AS report_scope, CAST('synthetic_crm' AS STRING) AS crm_source_system, CAST('crm-a' AS STRING) AS crm_source_scope, CAST('UTC' AS STRING) AS report_timezone, CAST('2026-01-01' AS DATE) AS report_start, CAST('2026-01-31' AS DATE) AS report_end, CAST('cohort' AS STRING) AS date_mode, CAST('won' AS STRING) AS stage_key, TRUE AS source_complete, TRUE AS report_complete, CAST('synthetic-source' AS STRING) AS source_evidence_ref, CAST('synthetic-report' AS STRING) AS report_evidence_ref;
CREATE OR REPLACE TEMP TABLE source_input AS
SELECT CAST('synthetic-check' AS STRING) AS invocation_key, CAST('synthetic_crm' AS STRING) AS source_system, CAST('crm-a' AS STRING) AS source_scope, CAST('Lead+A' AS STRING) AS lead_key, CAST('won' AS STRING) AS stage_key, CAST('2026-01-02' AS DATE) AS report_date, TRUE AS included, TRUE AS achieved, TRUE AS is_attribution_primary;
CREATE OR REPLACE TEMP TABLE report_input AS
SELECT CAST('synthetic-check' AS STRING) AS invocation_key, CAST('2026-01-02' AS DATE) AS report_date, CAST('won' AS STRING) AS stage_key, CAST('70' AS INT64) AS stage_order, CAST('won' AS STRING) AS stage_kind, CAST('Paid Search' AS STRING) AS channel, CAST('classified' AS STRING) AS channel_status, CAST('google_ads' AS STRING) AS network_id, CAST('Campaign+Case' AS STRING) AS campaign_key, CAST('synthetic_ads' AS STRING) AS ad_source_system, CAST('ads-a' AS STRING) AS ad_source_scope, CAST('matched' AS STRING) AS bucket, CAST('synthetic_crm' AS STRING) AS crm_source_system, CAST('crm-a' AS STRING) AS crm_source_scope, CAST('cohort' AS STRING) AS date_mode, CAST('UTC' AS STRING) AS report_timezone, CAST('0.1.0' AS STRING) AS taxonomy_version, CAST('1' AS INT64) AS lead_count, CAST('1' AS INT64) AS stage_count_total, CAST('1' AS INT64) AS stage_count_primary, CAST('0' AS INT64) AS stage_unknown_count;
-- END REPLACEABLE INPUTS
CREATE TEMP FUNCTION valid_key(v STRING) AS (v IS NOT NULL AND v!='' AND v=TRIM(v) AND NOT REGEXP_CONTAINS(v,r'[\x{0000}-\x{001F}\x{007F}-\x{009F}]'));
-- BEGIN SINGLE INVOCATION
ASSERT (SELECT COUNT(*)=1 FROM configuration_input) AS 'invalid configuration cardinality';
-- END SINGLE INVOCATION
ASSERT (SELECT TYPEOF(ANY_VALUE(invocation_key))='STRING' AND TYPEOF(ANY_VALUE(report_scope))='STRING' AND TYPEOF(ANY_VALUE(crm_source_system))='STRING' AND TYPEOF(ANY_VALUE(crm_source_scope))='STRING' AND TYPEOF(ANY_VALUE(report_timezone))='STRING' AND TYPEOF(ANY_VALUE(report_start))='DATE' AND TYPEOF(ANY_VALUE(report_end))='DATE' AND TYPEOF(ANY_VALUE(date_mode))='STRING' AND TYPEOF(ANY_VALUE(stage_key))='STRING' AND TYPEOF(ANY_VALUE(source_complete))='BOOL' AND TYPEOF(ANY_VALUE(report_complete))='BOOL' AND TYPEOF(ANY_VALUE(source_evidence_ref))='STRING' AND TYPEOF(ANY_VALUE(report_evidence_ref))='STRING' FROM configuration_input) AS 'invalid input column types';
ASSERT (SELECT TYPEOF(ANY_VALUE(invocation_key))='STRING' AND TYPEOF(ANY_VALUE(source_system))='STRING' AND TYPEOF(ANY_VALUE(source_scope))='STRING' AND TYPEOF(ANY_VALUE(lead_key))='STRING' AND TYPEOF(ANY_VALUE(stage_key))='STRING' AND TYPEOF(ANY_VALUE(report_date))='DATE' AND TYPEOF(ANY_VALUE(included))='BOOL' AND TYPEOF(ANY_VALUE(achieved))='BOOL' AND TYPEOF(ANY_VALUE(is_attribution_primary))='BOOL' FROM source_input) AS 'invalid input column types';
ASSERT (SELECT TYPEOF(ANY_VALUE(invocation_key))='STRING' AND TYPEOF(ANY_VALUE(report_date))='DATE' AND TYPEOF(ANY_VALUE(stage_key))='STRING' AND TYPEOF(ANY_VALUE(stage_order))='INT64' AND TYPEOF(ANY_VALUE(stage_kind))='STRING' AND TYPEOF(ANY_VALUE(channel))='STRING' AND TYPEOF(ANY_VALUE(channel_status))='STRING' AND TYPEOF(ANY_VALUE(network_id))='STRING' AND TYPEOF(ANY_VALUE(campaign_key))='STRING' AND TYPEOF(ANY_VALUE(ad_source_system))='STRING' AND TYPEOF(ANY_VALUE(ad_source_scope))='STRING' AND TYPEOF(ANY_VALUE(bucket))='STRING' AND TYPEOF(ANY_VALUE(crm_source_system))='STRING' AND TYPEOF(ANY_VALUE(crm_source_scope))='STRING' AND TYPEOF(ANY_VALUE(date_mode))='STRING' AND TYPEOF(ANY_VALUE(report_timezone))='STRING' AND TYPEOF(ANY_VALUE(taxonomy_version))='STRING' AND TYPEOF(ANY_VALUE(lead_count))='INT64' AND TYPEOF(ANY_VALUE(stage_count_total))='INT64' AND TYPEOF(ANY_VALUE(stage_count_primary))='INT64' AND TYPEOF(ANY_VALUE(stage_unknown_count))='INT64' FROM report_input) AS 'invalid input column types';
ASSERT NOT EXISTS(SELECT invocation_key FROM configuration_input GROUP BY 1 HAVING COUNT(*)!=1) AS 'invalid configuration cardinality';
ASSERT NOT EXISTS(SELECT 1 FROM configuration_input WHERE NOT valid_key(invocation_key) OR NOT valid_key(report_scope)
 OR NOT valid_key(crm_source_system) OR NOT valid_key(crm_source_scope) OR NOT valid_key(stage_key)
 OR NOT valid_key(source_evidence_ref) OR NOT valid_key(report_evidence_ref)
 OR source_complete IS NULL OR report_complete IS NULL OR report_start IS NULL OR report_end IS NULL OR report_start>report_end
 OR date_mode IS NULL OR date_mode NOT IN('cohort','activity') OR report_timezone IS NULL
 OR NOT REGEXP_CONTAINS(report_timezone,r'^[A-Za-z][A-Za-z0-9_+/-]*$')
 OR SAFE.FORMAT_TIMESTAMP('%F',TIMESTAMP '2026-01-01 00:00:00+00',report_timezone) IS NULL) AS 'invalid invocation configuration';
ASSERT NOT EXISTS(SELECT 1 FROM (SELECT invocation_key FROM source_input UNION ALL SELECT invocation_key FROM report_input) r LEFT JOIN configuration_input c USING(invocation_key) WHERE c.invocation_key IS NULL) AS 'missing invocation configuration';
ASSERT NOT EXISTS(SELECT 1 FROM source_input WHERE NOT valid_key(source_system) OR NOT valid_key(source_scope) OR NOT valid_key(lead_key) OR included IS NULL OR NOT valid_key(stage_key) OR is_attribution_primary IS NULL) AS 'invalid qualified source record';
ASSERT NOT EXISTS(SELECT 1 FROM source_input s JOIN configuration_input c USING(invocation_key)
 WHERE s.source_system=c.crm_source_system AND s.source_scope=c.crm_source_scope
 AND included!=(report_date IS NULL OR report_date BETWEEN report_start AND report_end)) AS 'invalid source inclusion';
ASSERT NOT EXISTS(SELECT invocation_key,source_system,source_scope,lead_key,stage_key FROM source_input GROUP BY 1,2,3,4,5 HAVING COUNT(DISTINCT TO_JSON_STRING(source_input))>1) AS 'conflicting qualified source record';
CREATE OR REPLACE TEMP TABLE source_unique AS SELECT DISTINCT * FROM source_input;
ASSERT NOT EXISTS(SELECT 1 FROM report_input r JOIN configuration_input c USING(invocation_key)
 WHERE NOT valid_key(r.stage_key) OR r.stage_order IS NULL OR r.stage_kind IS NULL OR r.stage_kind NOT IN('lead','qualified','converted','won','event')
 OR r.channel IS NULL OR r.channel NOT IN('Paid Search','Paid Social','Paid Other','Organic Search','Organic Social','Email','SMS','Direct','Referral','Affiliate','Other')
 OR r.channel_status IS NULL OR r.channel_status NOT IN('classified','missing_attribution') OR (r.channel_status='missing_attribution' AND r.channel!='Other')
 OR r.taxonomy_version IS NULL OR r.taxonomy_version!='0.1.0' OR r.bucket IS NULL OR r.bucket NOT IN('matched','ambiguous','unmatched','unattributed','spend_only')
 OR r.crm_source_system IS NULL OR r.crm_source_scope IS NULL OR r.crm_source_system!=c.crm_source_system OR r.crm_source_scope!=c.crm_source_scope
 OR r.date_mode IS NULL OR r.date_mode!=c.date_mode OR r.report_timezone IS NULL OR r.report_timezone!=c.report_timezone
 OR (r.network_id IS NOT NULL AND NOT valid_key(r.network_id)) OR (r.campaign_key IS NOT NULL AND NOT valid_key(r.campaign_key))
 OR ((r.ad_source_system IS NULL)!=(r.ad_source_scope IS NULL)) OR (r.ad_source_system IS NOT NULL AND (NOT valid_key(r.ad_source_system) OR NOT valid_key(r.ad_source_scope)))
 OR (r.stage_key=c.stage_key AND r.report_date IS NOT NULL AND NOT(r.report_date BETWEEN c.report_start AND c.report_end))) AS 'invalid report metadata';
ASSERT NOT EXISTS(SELECT invocation_key,stage_key FROM report_input GROUP BY 1,2 HAVING COUNT(DISTINCT TO_JSON_STRING(STRUCT(stage_order,stage_kind)))>1) AS 'conflicting report stage metadata';
ASSERT NOT EXISTS(SELECT 1 FROM report_input WHERE lead_count IS NULL OR lead_count<0 OR stage_count_total IS NULL OR stage_count_total<0 OR stage_count_primary IS NULL OR stage_count_primary<0 OR stage_unknown_count IS NULL OR stage_unknown_count<0) AS 'invalid report counts';
CREATE OR REPLACE TEMP TABLE selected_source AS SELECT s.* FROM source_unique s JOIN configuration_input c USING(invocation_key) WHERE s.source_system=c.crm_source_system AND s.source_scope=c.crm_source_scope AND s.stage_key=c.stage_key AND included;
CREATE OR REPLACE TEMP TABLE selected_report AS SELECT r.* FROM report_input r JOIN configuration_input c USING(invocation_key) WHERE r.stage_key=c.stage_key;
CREATE OR REPLACE TEMP TABLE duplicate_grains AS SELECT invocation_key,report_date,COUNT(*) AS grain_rows FROM selected_report GROUP BY invocation_key,report_date,stage_key,stage_order,stage_kind,channel,channel_status,network_id,campaign_key,ad_source_system,ad_source_scope,bucket,crm_source_system,crm_source_scope,date_mode,report_timezone,taxonomy_version HAVING COUNT(*)>1;
CREATE OR REPLACE TEMP TABLE source_dates AS SELECT invocation_key,report_date,COUNT(*) AS lead_count,COUNTIF(achieved) AS stage_count_total,COUNTIF(achieved AND is_attribution_primary) AS stage_count_primary,COUNTIF(achieved IS NULL) AS stage_unknown_count FROM selected_source GROUP BY 1,2;
CREATE OR REPLACE TEMP TABLE report_dates AS SELECT invocation_key,report_date,SUM(CAST(lead_count AS BIGNUMERIC)) AS lead_count,SUM(CAST(stage_count_total AS BIGNUMERIC)) AS stage_count_total,SUM(CAST(stage_count_primary AS BIGNUMERIC)) AS stage_count_primary,SUM(CAST(stage_unknown_count AS BIGNUMERIC)) AS stage_unknown_count FROM selected_report GROUP BY 1,2;
CREATE OR REPLACE TEMP TABLE dates AS SELECT invocation_key,report_date FROM source_dates UNION DISTINCT SELECT invocation_key,report_date FROM report_dates;
CREATE OR REPLACE TEMP TABLE count_checks AS SELECT d.invocation_key,d.report_date,s.invocation_key IS NOT NULL AS source_present,r.invocation_key IS NOT NULL AS report_present,m.*,
 (SELECT COUNT(*) FROM duplicate_grains g WHERE g.invocation_key=d.invocation_key AND g.report_date IS NOT DISTINCT FROM d.report_date) AS duplicate_count,
 CASE WHEN NOT(c.source_complete AND c.report_complete) THEN 'unknown' WHEN m.source_count!=m.report_count THEN 'fail' ELSE 'pass' END AS status
 FROM dates d JOIN configuration_input c USING(invocation_key)
 LEFT JOIN source_dates s ON d.invocation_key=s.invocation_key AND d.report_date IS NOT DISTINCT FROM s.report_date
 LEFT JOIN report_dates r ON d.invocation_key=r.invocation_key AND d.report_date IS NOT DISTINCT FROM r.report_date,
 UNNEST([STRUCT(0 AS metric_order,'lead_count' AS metric,CAST(IFNULL(s.lead_count,0) AS BIGNUMERIC) AS source_count,IFNULL(r.lead_count,0) AS report_count),
 STRUCT(1,'stage_count_total',CAST(IFNULL(s.stage_count_total,0) AS BIGNUMERIC),IFNULL(r.stage_count_total,0)),
 STRUCT(2,'stage_count_primary',CAST(IFNULL(s.stage_count_primary,0) AS BIGNUMERIC),IFNULL(r.stage_count_primary,0)),
 STRUCT(3,'stage_unknown_count',CAST(IFNULL(s.stage_unknown_count,0) AS BIGNUMERIC),IFNULL(r.stage_unknown_count,0))]) m;
CREATE OR REPLACE TEMP TABLE detail_base AS SELECT d.invocation_key,d.report_date,ANY_VALUE(source_present) AS source_present,ANY_VALUE(report_present) AS report_present,CAST(ANY_VALUE(duplicate_count) AS STRING) AS duplicate_grain_count,
 ARRAY_AGG(STRUCT(metric,CAST(source_count AS STRING) AS source_count,CAST(report_count AS STRING) AS report_count,CAST(report_count-source_count AS STRING) AS difference,status) ORDER BY metric_order) AS metrics,
 MAX(duplicate_count)>0 AS has_duplicate,COUNTIF(status='fail')>0 AS has_mismatch,ANY_VALUE(c.source_complete) AS source_complete,ANY_VALUE(c.report_complete) AS report_complete
 FROM count_checks d JOIN configuration_input c USING(invocation_key) GROUP BY 1,2;
CREATE OR REPLACE TEMP TABLE details AS SELECT * EXCEPT(has_duplicate,has_mismatch,source_complete,report_complete),
 CASE WHEN has_duplicate OR has_mismatch THEN 'fail' WHEN NOT(source_complete AND report_complete) THEN 'unknown' ELSE 'pass' END AS status,
 ARRAY(SELECT reason FROM UNNEST([IF(has_duplicate,'duplicate_report_grain',NULL),IF(has_mismatch,'count_mismatch',NULL),IF(NOT source_complete,'source_incomplete',NULL),IF(NOT report_complete,'report_incomplete',NULL)]) reason WHERE reason IS NOT NULL ORDER BY reason) AS reasons FROM detail_base;
CREATE OR REPLACE TEMP TABLE detail_summary AS SELECT invocation_key,COUNTIF(status='fail')>0 AS has_fail,COUNTIF(status='unknown')>0 AS has_unknown,COUNT(*) AS compared_dates,ARRAY_AGG(STRUCT(d.report_date AS report_date,d.source_present AS source_present,d.report_present AS report_present,d.duplicate_grain_count AS duplicate_grain_count,d.metrics AS metrics,d.status AS status,d.reasons AS reasons) ORDER BY report_date) AS detail_rows FROM details d GROUP BY 1;
CREATE OR REPLACE TEMP TABLE reason_summary AS SELECT invocation_key,ARRAY_AGG(DISTINCT reason ORDER BY reason) AS reason_rows FROM details d,UNNEST(d.reasons) reason GROUP BY 1;
CREATE OR REPLACE TEMP TABLE raw_source_summary AS SELECT invocation_key,COUNT(*) AS raw_rows FROM source_input GROUP BY 1;
CREATE OR REPLACE TEMP TABLE source_scope_status AS SELECT s.*,s.source_system=c.crm_source_system AND s.source_scope=c.crm_source_scope AS is_member FROM source_unique s JOIN configuration_input c USING(invocation_key);
CREATE OR REPLACE TEMP TABLE source_summary AS SELECT s.invocation_key,COUNT(*) AS unique_rows,COUNTIF(s.is_member AND s.included AND s.stage_key=c.stage_key) AS selected_rows,COUNTIF(NOT is_member) AS nonmember_rows,COUNTIF(NOT included) AS excluded_rows FROM source_scope_status s JOIN configuration_input c USING(invocation_key) GROUP BY 1;
CREATE OR REPLACE TEMP TABLE report_summary AS SELECT r.invocation_key,COUNT(*) AS raw_rows,COUNTIF(r.stage_key!=c.stage_key) AS other_stage_rows,COUNTIF(r.stage_key=c.stage_key) AS selected_rows FROM report_input r JOIN configuration_input c USING(invocation_key) GROUP BY 1;
CREATE OR REPLACE TEMP TABLE duplicate_summary AS SELECT invocation_key,COUNT(*) AS duplicate_grains FROM duplicate_grains GROUP BY 1;
-- BEGIN RESULT
SELECT c.invocation_key,TO_JSON_STRING(STRUCT('funnel_additivity' AS check_id,'0.1.0' AS contract_version,STRUCT(c.invocation_key AS invocation_key,c.report_scope AS report_scope,c.crm_source_system AS crm_source_system,c.crm_source_scope AS crm_source_scope,c.report_timezone AS report_timezone,c.report_start AS report_start,c.report_end AS report_end,c.date_mode AS date_mode,c.stage_key AS stage_key,c.source_complete AS source_complete,c.report_complete AS report_complete,c.source_evidence_ref AS source_evidence_ref,c.report_evidence_ref AS report_evidence_ref) AS configuration,
CASE WHEN IFNULL(d.has_fail,FALSE) THEN 'fail' WHEN NOT(c.source_complete AND c.report_complete) OR IFNULL(d.has_unknown,FALSE) THEN 'unknown' ELSE 'pass' END AS status,
ARRAY(SELECT DISTINCT reason FROM UNNEST(ARRAY_CONCAT([IF(NOT c.source_complete,'source_incomplete',NULL),IF(NOT c.report_complete,'report_incomplete',NULL)],IFNULL(z.reason_rows,[]))) reason WHERE reason IS NOT NULL ORDER BY reason) AS reasons,[c.source_evidence_ref,c.report_evidence_ref] AS evidence_refs,IFNULL(d.detail_rows,[]) AS details,
STRUCT(CAST(IFNULL(raw.raw_rows,0) AS STRING) AS source_raw_rows,CAST(IFNULL(raw.raw_rows,0)-IFNULL(s.unique_rows,0) AS STRING) AS source_duplicate_rows_collapsed,CAST(IFNULL(s.selected_rows,0) AS STRING) AS source_selected_rows,CAST(IFNULL(s.nonmember_rows,0) AS STRING) AS source_nonmember_rows,CAST(IFNULL(s.excluded_rows,0) AS STRING) AS source_excluded_rows,CAST(IFNULL(r.raw_rows,0) AS STRING) AS report_raw_rows,CAST(IFNULL(r.other_stage_rows,0) AS STRING) AS report_other_stage_rows,CAST(IFNULL(r.selected_rows,0) AS STRING) AS report_selected_rows,CAST(IFNULL(g.duplicate_grains,0) AS STRING) AS duplicate_report_grains,CAST(IFNULL(d.compared_dates,0) AS STRING) AS compared_dates) AS diagnostics)) AS result_json FROM configuration_input c LEFT JOIN detail_summary d USING(invocation_key) LEFT JOIN reason_summary z USING(invocation_key) LEFT JOIN raw_source_summary raw USING(invocation_key) LEFT JOIN source_summary s USING(invocation_key) LEFT JOIN report_summary r USING(invocation_key) LEFT JOIN duplicate_summary g USING(invocation_key) ORDER BY invocation_key;
