-- Native BigQuery Standard SQL. Temporary synthetic inputs only.
-- BEGIN REPLACEABLE INPUTS
CREATE OR REPLACE TEMP TABLE configuration_input AS
SELECT CAST('synthetic-check' AS STRING) AS invocation_key, CAST('synthetic-window' AS STRING) AS report_scope, CAST('UTC' AS STRING) AS report_timezone, CAST('2026-01-01' AS DATE) AS report_start, CAST('2026-01-01' AS DATE) AS report_end, CAST('cohort' AS STRING) AS date_mode, CAST('synthetic-source' AS STRING) AS source_evidence_ref, CAST('synthetic-report' AS STRING) AS report_evidence_ref, CAST('leads' AS STRING) AS metric_name, CAST('count' AS STRING) AS unit, CAST('0' AS NUMERIC) AS abs_tolerance, CAST('0' AS NUMERIC) AS relative_tolerance;
CREATE OR REPLACE TEMP TABLE membership_input AS
SELECT CAST('synthetic-check' AS STRING) AS invocation_key, CAST('synthetic_crm' AS STRING) AS source_system, CAST('crm-a' AS STRING) AS source_scope, TRUE AS reference_complete, TRUE AS observed_complete, CAST('reference-a' AS STRING) AS reference_evidence_ref, CAST('observed-a' AS STRING) AS observed_evidence_ref;
CREATE OR REPLACE TEMP TABLE reference_input AS
SELECT CAST('synthetic-check' AS STRING) AS invocation_key, CAST('synthetic_crm' AS STRING) AS source_system, CAST('crm-a' AS STRING) AS source_scope, CAST('2026-01-01' AS DATE) AS event_date, CAST('2' AS INT64) AS count, CAST('synthetic-window' AS STRING) AS report_scope, CAST('UTC' AS STRING) AS report_timezone, CAST('cohort' AS STRING) AS date_mode, CAST('leads' AS STRING) AS metric_name;
CREATE OR REPLACE TEMP TABLE observed_input AS
SELECT CAST('synthetic-check' AS STRING) AS invocation_key, CAST('synthetic_crm' AS STRING) AS source_system, CAST('crm-a' AS STRING) AS source_scope, CAST('2026-01-01' AS DATE) AS event_date, CAST('2' AS INT64) AS count, CAST('synthetic-window' AS STRING) AS report_scope, CAST('UTC' AS STRING) AS report_timezone, CAST('cohort' AS STRING) AS date_mode, CAST('leads' AS STRING) AS metric_name;
-- END REPLACEABLE INPUTS
CREATE TEMP FUNCTION valid_key(v STRING) AS (v IS NOT NULL AND v!='' AND v=TRIM(v) AND NOT REGEXP_CONTAINS(v,r'[\x{0000}-\x{001F}\x{007F}-\x{009F}]'));
-- BEGIN SINGLE INVOCATION
ASSERT (SELECT COUNT(*)=1 FROM configuration_input) AS 'invalid configuration cardinality';
-- END SINGLE INVOCATION
ASSERT (SELECT TYPEOF(ANY_VALUE(invocation_key))='STRING' AND TYPEOF(ANY_VALUE(report_scope))='STRING' AND TYPEOF(ANY_VALUE(report_timezone))='STRING' AND TYPEOF(ANY_VALUE(report_start))='DATE' AND TYPEOF(ANY_VALUE(report_end))='DATE' AND TYPEOF(ANY_VALUE(date_mode))='STRING' AND TYPEOF(ANY_VALUE(source_evidence_ref))='STRING' AND TYPEOF(ANY_VALUE(report_evidence_ref))='STRING' AND TYPEOF(ANY_VALUE(metric_name))='STRING' AND TYPEOF(ANY_VALUE(unit))='STRING' AND TYPEOF(ANY_VALUE(abs_tolerance))='NUMERIC' AND TYPEOF(ANY_VALUE(relative_tolerance))='NUMERIC' FROM configuration_input) AS 'invalid input column types';
ASSERT (SELECT TYPEOF(ANY_VALUE(invocation_key))='STRING' AND TYPEOF(ANY_VALUE(source_system))='STRING' AND TYPEOF(ANY_VALUE(source_scope))='STRING' AND TYPEOF(ANY_VALUE(reference_complete))='BOOL' AND TYPEOF(ANY_VALUE(observed_complete))='BOOL' AND TYPEOF(ANY_VALUE(reference_evidence_ref))='STRING' AND TYPEOF(ANY_VALUE(observed_evidence_ref))='STRING' FROM membership_input) AS 'invalid input column types';
ASSERT (SELECT TYPEOF(ANY_VALUE(invocation_key))='STRING' AND TYPEOF(ANY_VALUE(source_system))='STRING' AND TYPEOF(ANY_VALUE(source_scope))='STRING' AND TYPEOF(ANY_VALUE(event_date))='DATE' AND TYPEOF(ANY_VALUE(count))='INT64' AND TYPEOF(ANY_VALUE(report_scope))='STRING' AND TYPEOF(ANY_VALUE(report_timezone))='STRING' AND TYPEOF(ANY_VALUE(date_mode))='STRING' AND TYPEOF(ANY_VALUE(metric_name))='STRING' FROM reference_input) AS 'invalid input column types';
ASSERT (SELECT TYPEOF(ANY_VALUE(invocation_key))='STRING' AND TYPEOF(ANY_VALUE(source_system))='STRING' AND TYPEOF(ANY_VALUE(source_scope))='STRING' AND TYPEOF(ANY_VALUE(event_date))='DATE' AND TYPEOF(ANY_VALUE(count))='INT64' AND TYPEOF(ANY_VALUE(report_scope))='STRING' AND TYPEOF(ANY_VALUE(report_timezone))='STRING' AND TYPEOF(ANY_VALUE(date_mode))='STRING' AND TYPEOF(ANY_VALUE(metric_name))='STRING' FROM observed_input) AS 'invalid input column types';
ASSERT NOT EXISTS(SELECT invocation_key FROM configuration_input GROUP BY 1 HAVING COUNT(*)!=1) AS 'invalid configuration cardinality';
ASSERT NOT EXISTS(SELECT 1 FROM configuration_input WHERE NOT valid_key(invocation_key) OR NOT valid_key(report_scope) OR NOT valid_key(source_evidence_ref) OR NOT valid_key(report_evidence_ref)
 OR report_start IS NULL OR report_end IS NULL OR report_start>report_end OR date_mode IS NULL OR date_mode NOT IN('cohort','activity')
 OR report_timezone IS NULL OR NOT REGEXP_CONTAINS(report_timezone,r'^[A-Za-z][A-Za-z0-9_+/-]*$')
 OR SAFE.FORMAT_TIMESTAMP('%F',TIMESTAMP '2026-01-01 00:00:00+00',report_timezone) IS NULL) AS 'invalid invocation configuration';
ASSERT NOT EXISTS(SELECT 1 FROM configuration_input WHERE NOT valid_key(metric_name) OR unit IS NULL OR unit!='count' OR abs_tolerance IS NULL OR abs_tolerance<0 OR relative_tolerance IS NULL OR relative_tolerance<0 OR relative_tolerance>1) AS 'invalid parity configuration';
ASSERT NOT EXISTS(SELECT 1 FROM (SELECT invocation_key FROM membership_input UNION ALL SELECT invocation_key FROM reference_input UNION ALL SELECT invocation_key FROM observed_input) r LEFT JOIN configuration_input c USING(invocation_key) WHERE c.invocation_key IS NULL) AS 'missing invocation configuration';
ASSERT NOT EXISTS(SELECT 1 FROM membership_input WHERE NOT valid_key(source_system) OR NOT valid_key(source_scope)) AS 'invalid source membership';
ASSERT NOT EXISTS(SELECT 1 FROM configuration_input c LEFT JOIN membership_input m USING(invocation_key) WHERE m.invocation_key IS NULL) AS 'source membership is required';
ASSERT NOT EXISTS(SELECT 1 FROM membership_input WHERE reference_complete IS NULL OR observed_complete IS NULL OR NOT valid_key(reference_evidence_ref) OR NOT valid_key(observed_evidence_ref)) AS 'invalid membership evidence';
ASSERT NOT EXISTS(SELECT invocation_key,source_system,source_scope FROM membership_input GROUP BY 1,2,3 HAVING COUNT(DISTINCT TO_JSON_STRING(membership_input))>1) AS 'conflicting source membership';
CREATE OR REPLACE TEMP TABLE members AS SELECT DISTINCT * FROM membership_input;
ASSERT NOT EXISTS(SELECT 1 FROM reference_input r JOIN configuration_input c USING(invocation_key) WHERE NOT valid_key(source_system) OR NOT valid_key(source_scope) OR event_date IS NULL OR count IS NULL OR count<0
 OR r.report_scope IS NULL OR r.report_scope!=c.report_scope OR r.report_timezone IS NULL OR r.report_timezone!=c.report_timezone OR r.date_mode IS NULL OR r.date_mode!=c.date_mode OR r.metric_name IS NULL OR r.metric_name!=c.metric_name) AS 'invalid parity evidence';
ASSERT NOT EXISTS(SELECT invocation_key,source_system,source_scope,event_date FROM reference_input GROUP BY 1,2,3,4 HAVING COUNT(DISTINCT TO_JSON_STRING(reference_input))>1) AS 'conflicting qualified count record';
CREATE OR REPLACE TEMP TABLE reference_unique AS SELECT DISTINCT * FROM reference_input;
CREATE OR REPLACE TEMP TABLE reference_scoped AS SELECT r.*,m.invocation_key IS NOT NULL AS is_member,event_date BETWEEN c.report_start AND c.report_end AS in_window
 FROM reference_unique r LEFT JOIN members m USING(invocation_key,source_system,source_scope) JOIN configuration_input c USING(invocation_key);
CREATE OR REPLACE TEMP TABLE reference_raw_summary AS SELECT invocation_key,COUNT(*) AS raw_rows FROM reference_input GROUP BY 1;
CREATE OR REPLACE TEMP TABLE reference_summary AS SELECT invocation_key,COUNT(*) AS unique_rows,COUNTIF(is_member AND in_window) AS selected_rows,COUNTIF(NOT is_member) AS nonmember_rows,COUNTIF(NOT in_window) AS excluded_rows FROM reference_scoped GROUP BY 1;
ASSERT NOT EXISTS(SELECT 1 FROM observed_input r JOIN configuration_input c USING(invocation_key) WHERE NOT valid_key(source_system) OR NOT valid_key(source_scope) OR event_date IS NULL OR count IS NULL OR count<0
 OR r.report_scope IS NULL OR r.report_scope!=c.report_scope OR r.report_timezone IS NULL OR r.report_timezone!=c.report_timezone OR r.date_mode IS NULL OR r.date_mode!=c.date_mode OR r.metric_name IS NULL OR r.metric_name!=c.metric_name) AS 'invalid parity evidence';
ASSERT NOT EXISTS(SELECT invocation_key,source_system,source_scope,event_date FROM observed_input GROUP BY 1,2,3,4 HAVING COUNT(DISTINCT TO_JSON_STRING(observed_input))>1) AS 'conflicting qualified count record';
CREATE OR REPLACE TEMP TABLE observed_unique AS SELECT DISTINCT * FROM observed_input;
CREATE OR REPLACE TEMP TABLE observed_scoped AS SELECT r.*,m.invocation_key IS NOT NULL AS is_member,event_date BETWEEN c.report_start AND c.report_end AS in_window
 FROM observed_unique r LEFT JOIN members m USING(invocation_key,source_system,source_scope) JOIN configuration_input c USING(invocation_key);
CREATE OR REPLACE TEMP TABLE observed_raw_summary AS SELECT invocation_key,COUNT(*) AS raw_rows FROM observed_input GROUP BY 1;
CREATE OR REPLACE TEMP TABLE observed_summary AS SELECT invocation_key,COUNT(*) AS unique_rows,COUNTIF(is_member AND in_window) AS selected_rows,COUNTIF(NOT is_member) AS nonmember_rows,COUNTIF(NOT in_window) AS excluded_rows FROM observed_scoped GROUP BY 1;

CREATE OR REPLACE TEMP TABLE date_grid AS SELECT m.*,event_date FROM members m JOIN configuration_input c USING(invocation_key),UNNEST(GENERATE_DATE_ARRAY(c.report_start,c.report_end)) event_date;
CREATE OR REPLACE TEMP TABLE comparisons AS SELECT g.*,r.invocation_key IS NOT NULL AS reference_present,o.invocation_key IS NOT NULL AS observed_present,
 IF(r.invocation_key IS NULL AND NOT reference_complete,NULL,CAST(IFNULL(r.count,0) AS BIGNUMERIC)) AS reference_count,
 IF(o.invocation_key IS NULL AND NOT observed_complete,NULL,CAST(IFNULL(o.count,0) AS BIGNUMERIC)) AS observed_count
 FROM date_grid g LEFT JOIN reference_scoped r USING(invocation_key,source_system,source_scope,event_date) LEFT JOIN observed_scoped o USING(invocation_key,source_system,source_scope,event_date);
CREATE OR REPLACE TEMP TABLE bounds AS SELECT p.*,GREATEST(CAST(abs_tolerance AS BIGNUMERIC),ABS(reference_count)*relative_tolerance) AS allowed_difference FROM comparisons p JOIN configuration_input c USING(invocation_key);
CREATE OR REPLACE TEMP TABLE findings AS SELECT *,CASE WHEN NOT(reference_complete AND observed_complete) THEN 'unknown' WHEN ABS(observed_count-reference_count)>allowed_difference THEN 'fail' ELSE 'pass' END AS status,
 ARRAY(SELECT reason FROM UNNEST([IF(NOT reference_complete,'reference_incomplete',NULL),IF(NOT observed_complete,'observed_incomplete',NULL),
 IF(reference_complete AND observed_complete AND ABS(observed_count-reference_count)>allowed_difference,'count_mismatch',NULL)]) reason WHERE reason IS NOT NULL ORDER BY reason) AS reasons FROM bounds;
CREATE OR REPLACE TEMP TABLE detail_summary AS SELECT invocation_key,COUNT(*) AS compared_groups,COUNTIF(NOT reference_present) AS missing_reference_groups,COUNTIF(NOT observed_present) AS missing_observed_groups,
 COUNTIF(status='fail')>0 AS has_fail,COUNTIF(status='unknown')>0 AS has_unknown,
 ARRAY_AGG(STRUCT(source_system,source_scope,event_date,reference_complete,observed_complete,reference_present,observed_present,CAST(reference_count AS STRING) AS reference_count,CAST(observed_count AS STRING) AS observed_count,CAST(observed_count-reference_count AS STRING) AS difference,CAST(allowed_difference AS STRING) AS allowed_difference,status,reasons,[reference_evidence_ref,observed_evidence_ref] AS evidence_refs) ORDER BY source_system,source_scope,event_date) AS details
 FROM findings GROUP BY 1;
CREATE OR REPLACE TEMP TABLE reason_summary AS SELECT invocation_key,ARRAY_AGG(DISTINCT reason ORDER BY reason) AS reasons FROM findings,UNNEST(reasons) reason GROUP BY 1;
-- BEGIN RESULT
SELECT c.invocation_key,TO_JSON_STRING(STRUCT('source_parity' AS check_id,'0.1.0' AS contract_version,
 STRUCT(c.invocation_key AS invocation_key,c.report_scope AS report_scope,c.report_timezone AS report_timezone,c.report_start AS report_start,c.report_end AS report_end,c.date_mode AS date_mode,c.source_evidence_ref AS source_evidence_ref,c.report_evidence_ref AS report_evidence_ref,c.metric_name AS metric_name,c.unit AS unit,CAST(c.abs_tolerance AS STRING) AS abs_tolerance,CAST(c.relative_tolerance AS STRING) AS relative_tolerance) AS configuration,CASE WHEN d.has_fail THEN 'fail' WHEN d.has_unknown THEN 'unknown' ELSE 'pass' END AS status,
 IFNULL(z.reasons,[]) AS reasons,[c.source_evidence_ref,c.report_evidence_ref] AS evidence_refs,d.details,
 STRUCT(CAST(IFNULL(rraw.raw_rows,0) AS STRING) AS reference_raw_rows,CAST(IFNULL(rraw.raw_rows,0)-IFNULL(r.unique_rows,0) AS STRING) AS reference_duplicate_rows_collapsed,CAST(IFNULL(r.selected_rows,0) AS STRING) AS reference_selected_rows,CAST(IFNULL(r.nonmember_rows,0) AS STRING) AS reference_nonmember_rows,CAST(IFNULL(r.excluded_rows,0) AS STRING) AS reference_excluded_rows,CAST(IFNULL(oraw.raw_rows,0) AS STRING) AS observed_raw_rows,CAST(IFNULL(oraw.raw_rows,0)-IFNULL(o.unique_rows,0) AS STRING) AS observed_duplicate_rows_collapsed,CAST(IFNULL(o.selected_rows,0) AS STRING) AS observed_selected_rows,CAST(IFNULL(o.nonmember_rows,0) AS STRING) AS observed_nonmember_rows,CAST(IFNULL(o.excluded_rows,0) AS STRING) AS observed_excluded_rows,CAST(d.compared_groups AS STRING) AS compared_groups,CAST(d.missing_reference_groups AS STRING) AS missing_reference_groups,CAST(d.missing_observed_groups AS STRING) AS missing_observed_groups) AS diagnostics)) AS result_json FROM configuration_input c JOIN detail_summary d USING(invocation_key) LEFT JOIN reason_summary z USING(invocation_key)
 LEFT JOIN reference_raw_summary rraw USING(invocation_key) LEFT JOIN reference_summary r USING(invocation_key) LEFT JOIN observed_raw_summary oraw USING(invocation_key) LEFT JOIN observed_summary o USING(invocation_key) ORDER BY invocation_key;
