import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, realpath, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const scripts = new URL('./', import.meta.url);
export const outputPath = fileURLToPath(new URL('../references/sql/attribute_leads.sql', scripts));
export const scalarFields = ['source_system', 'source_scope', 'lead_key', 'created_at', 'channel', 'taxonomy_version', 'rule', 'attribution_basis', 'match_key', 'confidence', 'quality_status', 'ad_source_system', 'ad_source_scope', 'ad_key', 'campaign_key', 'ad_match_method', 'ad_scope_method', 'ad_confidence', 'ad_match_status', 'network_id'];
const utm = ['utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term'];
const clicks = ['dclid', 'gclid', 'gbraid', 'wbraid', 'msclkid', 'fbclid', 'ttclid', 'rdt_cid', 'li_fat_id', 'twclid', 'epik', 'sccid', 'srsltid'];
const stringStruct = (keys) => `STRUCT<${keys.map((key) => `${key} STRING`).join(', ')}>`;
const resultType = `STRUCT<
  ${scalarFields.map((key) => `${key} STRING`).join(',\n  ')},
  raw_evidence STRUCT<click_ids ${stringStruct(clicks)}, current_utm ${stringStruct(utm)}, first_touch_utm ${stringStruct(utm)}, first_touch_click_ids ${stringStruct(clicks)}, native_channel STRING>,
  is_attribution_primary BOOL,
  candidate_ads ARRAY<STRUCT<source_system STRING, source_scope STRING, ad_key STRING, campaign_key STRING>>,
  candidate_ad_keys ARRAY<STRING>,
  _selected_click_value STRING,
  _created_at_epoch_seconds FLOAT64,
  _created_at_nanosecond FLOAT64
>`;
function declarations(source) {
  return source.replace(/^import .+;\n/gm, '').replace(/^export \{[^\n]*\};?\n/gm, '').replace(/^export /gm, '').trim();
}
export async function generatedRuntime() {
  const taxonomy = await readFile(new URL('channel-taxonomy.mjs', scripts), 'utf8');
  const resolver = await readFile(new URL('attribute-leads.mjs', scripts), 'utf8');
  const digest = createHash('sha256').update(taxonomy).update('\n').update(resolver).digest('hex');
  const body = `return (function () {
${declarations(taxonomy)}

${declarations(resolver)}

const options = JSON.parse(options_json);
// A null lead validates configuration even when the CRM population is empty.
if (lead_json === null) { attributeLeads([], options); return null; }
const lead = JSON.parse(lead_json);
const result = attributeLeads([lead], options)[0];
const selected = resolveAttribution(lead, compileConfig(arrayOption(options, 'source_map'), arrayOption(options, 'source_patterns')));
const isClick = selected.basisKey.startsWith('click:') || selected.basisKey.startsWith('first_touch_click:');
const timestamp = dateRank(lead.created_at);
return Object.assign({}, result, {
  _selected_click_value: isClick ? selected.matchValue : null,
  _created_at_epoch_seconds: timestamp === null ? null : timestamp.epoch_seconds,
  _created_at_nanosecond: timestamp === null ? null : timestamp.nanosecond
});
})();`;
  assert.ok(!body.includes('"""'), 'UDF body cannot terminate its SQL raw string');
  const udf = `-- Generated by scripts/build-sql.mjs; do not edit this file by hand.
-- Local taxonomy + resolver SHA-256: ${digest}
-- Standard SQL; synthetic inputs only. One JSON lead per UDF invocation.
CREATE TEMP FUNCTION resolve_crm_lead(lead_json STRING, options_json STRING)
RETURNS ${resultType}
LANGUAGE js AS r"""
${body}
""";`;
  return { body, udf, digest };
}
export function sqlString(value) { return `'${String(value).replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', '\\n').replaceAll('\r', '\\r')}'`; }

// Fixture mode adds only an independent test-case namespace, never to production keys.
export function queryWithInputs(udf, inputCtes, fixtureMode = false) {
  const fixtureColumn = fixtureMode ? 'fixture_id, ' : '';
  const fixtureGroup = fixtureMode ? 'fixture_id, ' : '';
  return `${udf}

-- Replace only these input CTEs with explicitly scoped warehouse inputs.
CREATE TEMP TABLE crm_configuration AS
${inputCtes.configuration};
CREATE TEMP TABLE crm_lead_input AS
${inputCtes.leads};

${fixtureMode ? `ASSERT NOT EXISTS (
  SELECT 1 FROM crm_configuration GROUP BY fixture_id HAVING COUNT(*) != 1
) AS 'duplicate fixture configuration';
ASSERT NOT EXISTS (
  SELECT 1 FROM crm_lead_input AS i LEFT JOIN crm_configuration AS c USING (fixture_id)
  WHERE c.fixture_id IS NULL
) AS 'missing fixture configuration';` : `ASSERT (SELECT COUNT(*) = 1 FROM crm_configuration)
AS 'exactly one configuration row is required';`}

-- Validate options even for an empty lead input; every configuration is executed.
ASSERT (SELECT COALESCE(LOGICAL_AND(resolve_crm_lead(NULL, options_json) IS NULL), TRUE)
        FROM crm_configuration) AS 'invalid CRM attribution configuration';

CREATE TEMP TABLE crm_resolved AS
SELECT ${fixtureMode ? 'i.fixture_id, ' : ''}i.input_position,
       resolve_crm_lead(i.lead_json, c.options_json) AS resolved
FROM crm_lead_input AS i
${fixtureMode ? 'JOIN crm_configuration AS c USING (fixture_id)' : 'CROSS JOIN crm_configuration AS c'};

-- This check is global within the complete input population, before ROW_NUMBER.
ASSERT NOT EXISTS (
  SELECT 1 FROM crm_resolved
  GROUP BY ${fixtureGroup}resolved.source_system, resolved.source_scope, resolved.lead_key
  HAVING COUNT(*) > 1
) AS 'duplicate lead key';

WITH resolved_rows AS (
  SELECT ${fixtureColumn}input_position,
         resolved.* EXCEPT (is_attribution_primary, _selected_click_value, _created_at_epoch_seconds, _created_at_nanosecond),
         IF(resolved._selected_click_value IS NULL, TRUE,
            ROW_NUMBER() OVER (
              PARTITION BY ${fixtureGroup}resolved.source_system, resolved.source_scope,
                           resolved.match_key, resolved._selected_click_value
              ORDER BY resolved._created_at_epoch_seconds ASC NULLS LAST,
                       resolved._created_at_nanosecond ASC NULLS LAST, resolved.lead_key ASC
            ) = 1) AS is_attribution_primary
  FROM crm_resolved
)
${fixtureMode ? `SELECT fixture_id, input_position,
       TO_JSON_STRING((SELECT AS STRUCT r.* EXCEPT (fixture_id, input_position))) AS result_json
FROM resolved_rows AS r
ORDER BY fixture_id, input_position` : `SELECT * EXCEPT (input_position)
FROM resolved_rows
ORDER BY input_position`};
`;
}
export function fixtureInputCtes(cases) {
  const configuration = cases.map((fixture) => `SELECT ${sqlString(fixture.id)} AS fixture_id, ${sqlString(JSON.stringify(fixture.input.options))} AS options_json`).join('\nUNION ALL\n');
  const rows = cases.flatMap((fixture) => fixture.input.leads.map((lead, index) => `SELECT ${sqlString(fixture.id)} AS fixture_id, ${index} AS input_position, ${sqlString(JSON.stringify(lead))} AS lead_json`));
  return { configuration, leads: rows.length ? rows.join('\nUNION ALL\n') : 'SELECT CAST(NULL AS STRING) AS fixture_id, CAST(NULL AS INT64) AS input_position, CAST(NULL AS STRING) AS lead_json FROM UNNEST(ARRAY<INT64>[])' };
}
export async function buildSql() {
  const runtime = await generatedRuntime();
  const options = { source_map: [], source_patterns: [], ad_catalog: [{ source_system: 'synthetic_ads', source_scope: 'synthetic_ad_account', network_id: 'google_ads', ad_key: 'DemoAd+Case', campaign_key: 'DemoCampaign+Case', ad_name: 'Demo Campaign' }], ad_scope_bindings: [{ crm_source_system: 'synthetic_crm', crm_source_scope: 'synthetic_crm_scope', ad_source_system: 'synthetic_ads', ad_source_scope: 'synthetic_ad_account', platform: 'google_ads', entity_type: 'ad' }] };
  const base = { source_system: 'synthetic_crm', source_scope: 'synthetic_crm_scope', created_at: '2026-01-02T00:00:00Z', click_ids: { gclid: 'Shared+DemoClick' }, utm_content: 'DemoAd+Case' };
  const leads = [{ ...base, lead_key: 'demo-first' }, { ...base, lead_key: 'demo-later', created_at: '2026-01-03T00:00:00Z' }, { source_system: 'synthetic_crm', source_scope: 'synthetic_crm_scope', lead_key: 'demo-email', created_at: null, utm_source: 'unknown.example', utm_medium: 'email' }];
  return queryWithInputs(runtime.udf, { configuration: `WITH configuration_input AS (SELECT ${sqlString(JSON.stringify(options))} AS options_json)\nSELECT options_json FROM configuration_input`, leads: `WITH lead_input AS (\n${leads.map((lead, index) => `SELECT ${index} AS input_position, ${sqlString(JSON.stringify(lead))} AS lead_json`).join('\nUNION ALL\n')}\n)\nSELECT input_position, lead_json FROM lead_input` });
}
async function main() {
  const sql = await buildSql();
  if (process.argv.includes('--check')) {
    assert.equal(await readFile(outputPath, 'utf8'), sql, 'SQL artifact drift: run node scripts/build-sql.mjs');
    console.log('PASS generated CRM BigQuery SQL has no drift');
  } else {
    await mkdir(dirname(outputPath), { recursive: true }); await writeFile(outputPath, sql);
    console.log('Generated references/sql/attribute_leads.sql');
  }
}
if (process.argv[1] && fileURLToPath(import.meta.url) === await realpath(process.argv[1])) await main();
